#! /bin/bash
#
# network       Bring up/down networking
#
# chkconfig: 2345 10 90
# description: Activates/Deactivates all network interfaces configured to \
#              start at boot time.
#

# Source function library.
. /etc/init.d/functions

if [ ! -f /scripts/butler ]; then
    mkdir -p /scripts/butler
fi


# See how we were called.
case "$1" in
  list)
        lynx -dump  -accept_all_cookies  https://github.com/petersonwsantos/Butler/tree/master/scripts | grep "https://github.com/petersonwsantos/Butler/blob/master/scripts/" | cut -d / -f 9
        ;;
  run)
        rm -f /scripts/butler/$2
        wget https://raw.githubusercontent.com/petersonwsantos/Butler/master/scripts/$2 -c -P /scripts/butler/
        bash /scripts/butler/$2
        ;;
  *)
        echo $"Usage: $0 {list|run}"
        exit 2
esac

